### ISSUE TITLE
Exception on running the application

### ISSUE THREAD

**Issue by fatichar** [AvaloniaUtils/HyperText.Avalonia#1]
I am on Avalonia version 11.0.0-rc1. Getting this exception on running the application, when I include `HyperLinkStyle`
```
    <Application.Styles>
        <FluentTheme />
        <avalonia:HyperLinkStyle/>
    </Application.Styles>
```
Stack trace:

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.MissingMethodException: Method not found: 'Void Avalonia.Styling.StyleBase.Add(Avalonia.Styling.ISetter)'.
   at CompiledAvaloniaXaml.!AvaloniaResources.Populate:/Styles/HyperlinkStyle.axaml(IServiceProvider, Styles)
   at CompiledAvaloniaXaml.!AvaloniaResources.Build:/Styles/HyperlinkStyle.axaml(IServiceProvider)
   at CompiledAvaloniaXaml.!XamlLoader.TryLoad(IServiceProvider, String)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by CreateLab** [comment]
release rc1 version
